version: '3'
services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - 8000:8000
    command: bash -c "uvicorn main:app"
    env_file:
      - .env
    volumes:
      - ./fastapi.db:/app/fastapi.db:delegated
